# "org" ensures this Service is used with the correct Serverless Framework Access Key.
org: jecaicedo
service: hola-mundo

provider:
  name: aws
  runtime: python3.12
  region: us-east-1

functions:
  app:
    handler: app.main.handler
    events:
      - httpApi:
          path: /
          method: get

plugins:
  - serverless-python-requirements

custom:
  pythonRequirements:
    dockerizePip: true